server:
  port: 8761

spring:
  jmx:
    default-domain: mogu_eureka
  application:
    name: mogu-eureka
  security:
    user:
      name: user
      password: password123

eureka:
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 3000
    peer-node-connect-timeout-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka